# 100 numpy exercises

Source: https://github.com/rougier/numpy-100


#### How to run this notebook

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

#### How to get help

If you are stuck, you can ask for help on the community forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561 . You can get help with errors, ask for hints, and share your solutions with others.

If you're new to Numpy, check out this notebook for a quick tutorial: https://jovian.ml/aakashns/python-numerical-computing-with-numpy


#### Saving your work

Remember to save a snapshot of your work from time to time using to your Jovian.ml account.

In [1]:
!pip install jovian --upgrade --quiet

In [2]:
import jovian

In [3]:
jovian.commit(project='100-numpy-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Please enter your API key ( from https://jovian.ml/ ):
API KEY: ········
[jovian] Updating notebook "halovivek-qg0/100-numpy-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/100-numpy-exercises


'https://jovian.ml/halovivek-qg0/100-numpy-exercises'

`jovian.commit` uploads the notebook to your Jovian.ml account, captures the Python environment and creates a shareable link for your notebook as shown above. You can use this link to share your work and let anyone (including you) run your notebooks and reproduce your work. Learn more: https://jovian.ml/docs/


In [ ]:
# Ucomment the next line if you need install numpy
# !pip install numpy --upgrade

#### 1. Import the numpy package under the name `np` (★☆☆)

In [4]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)

1.19.1


#### 3. Create a null vector of size 10 (★☆☆)

In [8]:
import numpy as np
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [10]:
import numpy as np
n = np.zeros((4,4))
print("%d bytes" % (n.size* n.itemsize)) 

128 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
python -c  "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (<ipython-input-11-1663cd30cb7c>, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
X = np.zeros(10)
X[4] =1
print (X)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
X = np.arange(10,50)
print(X)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [17]:
x = np.arange(1,100)
x = x[::-1]
print(x)

[99 98 97 96 95 94 93 92 91 90 89 88 87 86 85 84 83 82 81 80 79 78 77 76
 75 74 73 72 71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52
 51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4
  3  2  1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [19]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
nonzero = np.nonzero([1,2,0,0,4,0])
print(nonzero)

(array([0, 1, 4]),)


Save your progress by commiting your work to Jovian

In [22]:
import jovian

In [23]:
jovian.commit(project='numpy-100-exercises')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Creating a new project "halovivek-qg0/numpy-100-exercises"
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
 x= np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [25]:
 x= np.random.uniform((3,3,3))
print(x)

[1.88028721 2.28847076 2.24847065]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [26]:
x = np.random.random((10,10))
xmin, xmax = x.min(),x.max()
print(xmin,xmax)

0.012709136434874257 0.956873801190057


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [27]:
x = np.random.random(10)
m = x.mean()
print(m)

0.4519555443807054


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
x = np.ones((10,10))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
import numpy as np
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [30]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [33]:
x = np.diag((1+np.arange(4)),k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [34]:
Z = np.zeros ((8,8), dtype=int)
Z[1::2, ::2]= 1
Z[::2, 1::2] = 1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [35]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


Save your progress by commiting your work to Jovian

In [36]:
import jovian

In [37]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [38]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [39]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)

[[0.2009366  0.         0.03831051 0.602244   0.60197176]
 [0.60813105 0.77450225 0.40017256 0.09595305 0.01454014]
 [0.34200101 0.10130142 0.84127453 0.0144415  1.        ]
 [0.22024985 0.21453506 0.08843703 0.83462323 0.20297929]
 [0.13876265 0.16804817 0.20738978 0.59891867 0.28360977]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [40]:
color = np.dtype([("r", np.ubyte, 1),
                 ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


<ipython-input-40-7bd752435f34>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("r", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [41]:
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [42]:
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [44]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
print(Z)

ValueError: Integers to negative integer powers are not allowed.

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [45]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


<ipython-input-45-2a10de0ee61b>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
<ipython-input-45-2a10de0ee61b>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print (np.copysign(np.ceil(np.abs(Z)), Z))


#### 30. How to find common values between two arrays? (★☆☆)

Save your progress by commiting your work to Jovian

In [ ]:
import jovian

In [ ]:
jovian.commit()

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
# Suicide mode on
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-3-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2020-09-02 2020-09-03 2020-09-04


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [7]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [8]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [9]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[4. 0. 0. 5. 7. 2. 2. 4. 4. 5.]
[4. 0. 0. 5. 7. 2. 2. 4. 4. 5.]
[4. 0. 0. 5. 7. 2. 2. 4. 4. 5.]
[4 0 0 5 7 2 2 4 4 5]
[4. 0. 0. 5. 7. 2. 2. 4. 4. 5.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [11]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [12]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.30482941 0.32626298 0.4324884  0.56835257 0.62420378 0.63187852
 0.65792065 0.78664616 0.89801269 0.99549268]


Save your progress by commiting your work to Jovian

In [14]:
import jovian

In [15]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [16]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [17]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [18]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [19]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.68468477 0.9181571  0.39439819 1.00700759 0.88053026 0.61866225
 0.70286631 0.58603932 0.84700707 0.45347715]
[0.23804344 0.00610962 0.5805361  0.20444578 0.01770714 0.91503535
 1.16996952 0.29783893 1.15124583 0.44736058]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [20]:
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.68029842 0.05185623 0.93746341 0.19348299 0.         0.9491968
 0.12149749 0.07524672 0.12308922 0.0449027 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [21]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [22]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [23]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [25]:
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [26]:
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])

94


Save and commit your work.

In [27]:
import jovian

In [28]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [29]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                  ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-29-442c537e74e6>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [30]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.724466   0.63132078 0.24451139 0.78157528 0.43605392
  0.78008511 0.26693736 0.04924965 0.94257068]
 [0.724466   0.         0.52138772 0.78805202 0.46116987 0.51526523
  0.45117751 0.53153918 0.76914286 0.25336739]
 [0.63132078 0.52138772 0.         0.51516587 0.91529491 0.76240782
  0.19203904 0.36972162 0.64960299 0.76127202]
 [0.24451139 0.78805202 0.51516587 0.         0.96067998 0.64387332
  0.69627908 0.25670529 0.22270117 1.03262629]
 [0.78157528 0.46116987 0.91529491 0.96067998 0.         0.358099
  0.89634678 0.74020282 0.83016062 0.42451725]
 [0.43605392 0.51526523 0.76240782 0.64387332 0.358099   0.
  0.81996286 0.47211729 0.48289797 0.64110861]
 [0.78008511 0.45117751 0.19203904 0.69627908 0.89634678 0.81996286
  0.         0.51323407 0.80559201 0.65727626]
 [0.26693736 0.53153918 0.36972162 0.25670529 0.74020282 0.47211729
  0.51323407 0.         0.2936276  0.77621607]
 [0.04924965 0.76914286 0.64960299 0.22270117 0.83016062 0.48289797
  0.80559201 0.2936276

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [31]:
Z = np.arange(10, dtype=np.float32)
Z = Z.astype(np.int32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [32]:
from io import StringIO

# Fake file
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [33]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [34]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [35]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [37]:
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
#Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

[[-0.10256599 -0.27977221  0.43090892  0.03189326  0.2904079  -0.39492099
  -0.4769056  -0.00711502  0.04528864  0.46278108]
 [-0.25003891  0.31498981 -0.04627938 -0.16535948 -0.08202054  0.54065961
  -0.3794268  -0.10604269  0.23617004 -0.06265165]
 [ 0.03764047  0.47479573  0.09386437 -0.49779135  0.17564839 -0.39053829
  -0.09256614  0.22239247 -0.12429737  0.10085173]
 [ 0.03760704 -0.22650287 -0.35599078  0.46700324 -0.11064896  0.57361962
  -0.38345603  0.09456429  0.06484534 -0.1610409 ]
 [-0.38813384  0.1615443   0.28566351 -0.06035836 -0.3386959  -0.2184463
   0.27387619  0.45294367 -0.0309975  -0.13739576]]


#### 59. How to sort an array by the nth column? (★★☆)

In [38]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 6 1]
 [3 2 8]
 [2 2 1]]
[[3 2 8]
 [2 2 1]
 [9 6 1]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [39]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


Save and commit your work.

In [40]:
import jovian

In [41]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 61. Find the nearest value from a given value in an array (★★☆)

In [42]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.47777507908864225


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [43]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [44]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [45]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)

[5. 4. 1. 1. 3. 3. 3. 4. 3. 3.]
[9. 7. 1. 1. 5. 5. 5. 7. 5. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [46]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [47]:
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*256*256 + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [48]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[41 53 56 30]
 [45 60 33 56]
 [67 56 52 72]]
[[41 53 56 30]
 [45 60 33 56]
 [67 56 52 72]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [49]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.43732286 0.49864489 0.56846748 0.5461407  0.70294257 0.58149778
 0.42704968 0.58547966 0.54929295 0.70907368]
0    0.437323
1    0.498645
2    0.568467
3    0.546141
4    0.702943
5    0.581498
6    0.427050
7    0.585480
8    0.549293
9    0.709074
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [50]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([0.6526072 , 1.10610565, 3.3950919 , 0.78364267, 1.7211405 ])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [51]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


Save and commit your work

In [52]:
import jovian

In [53]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [54]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [55]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [56]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[(16, 20) (16, 31) (20, 31) (20, 56) (20, 72) (21, 75) (21, 94) (30, 36)
 (30, 38) (30, 46) (30, 98) (31, 76) (31, 86) (36, 75) (36, 77) (36, 98)
 (38, 46) (43, 44) (43, 72) (44, 72) (51, 83) (51, 98) (56, 72) (56, 79)
 (56, 80) (75, 77) (75, 94) (76, 86) (79, 80) (83, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [57]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [58]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [59]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [60]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.84008758, -0.1260299 , -0.26069492,  0.74335045, -0.31089201,
        0.10955903,  0.55264187, -0.47808311, -0.80621594, -0.5416218 ,
        0.17194778, -0.18972343, -0.59194158,  0.05471824,  0.7335104 ,
       -0.18541124, -0.33120191, -0.84124919, -0.94997707,  0.94996793,
        0.34554491, -0.91999016, -0.38393282,  0.43439308,  0.78305045,
       -0.32086051, -0.75807854, -0.29885702,  0.95705378, -0.90271568,
        0.51454228, -0.56089277,  0.84724116, -0.59154537, -0.75996846,
        0.60223136, -0.45219164, -0.19435367,  0.04141243,  0.34745913,
       -0.29413836,  0.3761172 ,  0.63420125,  0.0518738 , -0.83154546,
       -0.24366282,  0.52478329, -0.7660947 ,  0.51728628,  0.18628816,
        0.56201976, -0.42119012,  0.00680853,  0.50622318, -0.75168342,
       -0.02127592,  0.70998367,  0.49154911,  0.5169994 ,  0.70290001,
        0.00747372, -0.51815804, -0.65537234, -0.10532013, -0.80369622,
       -0.69902133,  0.59656894, -0.86653234, -0.30573698, -0.54

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [61]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[5.78865413e+00 1.03449907e+01 1.03716846e+01 3.91713186e+00
 2.33304662e-01 1.17489071e+01 7.69263168e-03 6.66368352e+00
 2.94756857e+00 9.01893964e+00]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [62]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 4.63588856  9.37534436  7.3777512   7.38858319  9.44907571  7.6239208
  18.05850913  1.59621947  3.83310684  7.92440055]
 [ 2.32088189  3.08378518  3.12572147  4.99348545  2.50720903  1.69610471
   5.82621017  3.74240891  4.17074298  7.55209071]
 [ 7.52535624  1.86708391  3.01593362 11.87105877  0.26459925  8.12057423
   5.31260242  3.14343854 10.98654938 14.41580549]
 [ 3.29385487  0.24642233  8.4470678   1.39346103  0.33526761  0.45028879
  10.1859897   7.42975865  0.29061638  3.2941652 ]
 [ 9.52434305  4.97530009 14.06163011  1.75113128  3.22394121  1.76707556
  15.87100965 10.68870399  4.59756291  0.73024999]
 [ 4.14409495  8.338786    2.57039893  2.72880028  7.85303347  1.90790863
   0.98942214  5.90826187  3.01994037  6.10589261]
 [ 2.98156937  6.83652708  3.44382986  2.65207144  6.49966457  1.51477118
   2.55830929  6.01679536  2.60242825  5.77516076]
 [11.23806021  0.72569841 17.57313228  8.37643272  3.58211216  9.34463209
  11.69545891 17.2272276  10.14312978  6.58284239]
 

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [63]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 4 1 0 2 4 5 3 0 0]
 [5 3 4 5 5 0 2 1 6 7]
 [3 3 1 5 2 9 0 6 5 8]
 [3 4 4 4 6 7 7 8 6 4]
 [5 7 1 3 8 7 7 2 3 2]
 [0 9 9 0 5 0 8 5 8 1]
 [0 4 0 7 4 0 2 8 2 6]
 [2 6 9 5 7 7 8 1 5 3]
 [3 8 8 5 1 3 2 6 2 9]
 [4 7 0 2 5 9 8 1 8 7]]
[[0 0 0 0 0]
 [0 8 4 1 0]
 [0 5 3 4 5]
 [0 3 3 1 5]
 [0 3 4 4 4]]


<ipython-input-63-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


Save and commit your work.

In [64]:
import jovian

In [65]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [66]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [67]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [68]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [69]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 4 0]
   [3 3 4]
   [2 0 4]]

  [[4 0 2]
   [3 4 2]
   [0 4 0]]

  [[0 2 2]
   [4 2 4]
   [4 0 4]]

  [[2 2 3]
   [2 4 4]
   [0 4 3]]

  [[2 3 1]
   [4 4 0]
   [4 3 1]]

  [[3 1 0]
   [4 0 2]
   [3 1 3]]

  [[1 0 4]
   [0 2 1]
   [1 3 1]]

  [[0 4 1]
   [2 1 1]
   [3 1 3]]]


 [[[3 3 4]
   [2 0 4]
   [1 3 2]]

  [[3 4 2]
   [0 4 0]
   [3 2 4]]

  [[4 2 4]
   [4 0 4]
   [2 4 0]]

  [[2 4 4]
   [0 4 3]
   [4 0 2]]

  [[4 4 0]
   [4 3 1]
   [0 2 4]]

  [[4 0 2]
   [3 1 3]
   [2 4 0]]

  [[0 2 1]
   [1 3 1]
   [4 0 2]]

  [[2 1 1]
   [3 1 3]
   [0 2 2]]]


 [[[2 0 4]
   [1 3 2]
   [0 1 1]]

  [[0 4 0]
   [3 2 4]
   [1 1 2]]

  [[4 0 4]
   [2 4 0]
   [1 2 4]]

  [[0 4 3]
   [4 0 2]
   [2 4 3]]

  [[4 3 1]
   [0 2 4]
   [4 3 0]]

  [[3 1 3]
   [2 4 0]
   [3 0 4]]

  [[1 3 1]
   [4 0 2]
   [0 4 1]]

  [[3 1 3]
   [0 2 2]
   [4 1 2]]]


 [[[1 3 2]
   [0 1 1]
   [2 3 2]]

  [[3 2 4]
   [1 1 2]
   [3 2 2]]

  [[2 4 0]
   [1 2 4]
   [2 2 1]]

  [[4 0 2]
   [2 4 3]
   [2 1 2]]

  [[0 2 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [70]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  6 10  5 11]
 [ 6  0  3 10 16]
 [10  3  9 42 11]
 [ 5 10 42  0  5]
 [11 16 11  5  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [71]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [72]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [74]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)

In [75]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [76]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]
    
    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


Save and commit your work

In [77]:
import jovian

In [78]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

#### 91. How to create a record array from a regular array? (★★★)

In [79]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [80]:
x = np.random.rand(5e7)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [81]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [82]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 4 3]
 [1 3 2]
 [2 1 3]
 [0 2 4]
 [2 3 0]
 [2 1 3]
 [4 3 3]
 [4 4 3]
 [2 4 0]
 [0 1 0]]
[[2 4 3]
 [1 3 2]
 [2 1 3]
 [0 2 4]
 [2 3 0]
 [2 1 3]
 [4 3 3]
 [4 4 3]
 [2 4 0]
 [0 1 0]]
[[2 4 3]
 [1 3 2]
 [2 1 3]
 [0 2 4]
 [2 3 0]
 [2 1 3]
 [4 3 3]
 [4 4 3]
 [2 4 0]
 [0 1 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [83]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [84]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]]
[[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [85]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.20178491, 0.10671066, 0.27141848, 0.16609934, 0.15380274,
        0.2504117 , 0.25656796, 0.1352287 , 0.10646985, 0.10914273],
       [0.50713098, 0.26818796, 0.68213585, 0.41744509, 0.38654097,
        0.62934107, 0.64481313, 0.33986023, 0.26758274, 0.2743003 ],
       [0.20479711, 0.10830362, 0.27547016, 0.16857883, 0.15609868,
        0.25414979, 0.26039795, 0.13724737, 0.10805921, 0.11077199],
       [0.41106339, 0.21738418, 0.55291648, 0.33836702, 0.31331717,
        0.5101228 , 0.52266393, 0.27547932, 0.21689361, 0.22233864],
       [0.61448727, 0.32496158, 0.82653952, 0.50581548, 0.46836915,
        0.76256843, 0.78131583, 0.4118064 , 0.32422825, 0.33236787],
       [0.11927088, 0.06307446, 0.16042983, 0.09817787, 0.09090961,
        0.14801316, 0.151652  , 0.07993088, 0.06293212, 0.06451201],
       [0.08368802, 0.04425704, 0.11256775, 0.06888783, 0.06378795,
        0.10385543, 0.10640867, 0.05608458, 0.04415717, 0.04526572],
       [0.56621317, 0.29943261, 0.7616066

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [90]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [91]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [92]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.30790845  0.09319345]


Save and commit your work

In [93]:
import jovian

In [94]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "halovivek-qg0/numpy-100-exercises" on https://jovian.ml/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ml/halovivek-qg0/numpy-100-exercises


'https://jovian.ml/halovivek-qg0/numpy-100-exercises'

Congratulations on completing the 100 exercises, well done!

#### What to do next?

- Share your completed notebook on Facebook, LinkedIn or Twitter and challenge your friends.
- Share your solutions and help others on the forum: https://jovian.ml/forum/t/100-numpy-exercises-hints-discussions-help/10561
- Check out our course on "Data Analysis with Python: Zero to Pandas" - https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas
- Star this repository to show your appreciation for the original author of this notebook: https://github.com/rougier/numpy-100